name: Package

on:
  push:
    branches:
      - main

jobs:
  package:
    name: Package RPMs
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: dnf install -y rpmdevtools rpm-sign createrepo

      - name: Run .ci/build.sh
        run: .ci/build.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Run .ci/deploy.sh
        run: .ci/deploy.sh
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
          SFTP_PATH: ${{ secrets.SFTP_PATH }}
